server:
  port: 8080

spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  resources:
    static-locations: "classpath:/static/"

okta:
  oauth2:
    issuer: https://dev-909736.oktapreview.com/oauth2/default
    clientId: 0oagn5z32uPSmSXqR0h7
    clientSecret: MmqhXPFtdkXoVbZipr0uTuerJF7JVdYiWW5Srwyj
    rolesClaim: groups